language: python
matrix:
  include:
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.7
      env: TOXENV=pep8
    - python: 3.7
      env: TOXENV=coverage
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install tox
before_script:
  - npm install
  - npm run build
script:
  - tox -e $TOXENV
addons:
  ssh_known_hosts: yacoma.it
after_success:
  - openssl aes-256-cbc -K $encrypted_cd8ac8b45767_key -iv $encrypted_cd8ac8b45767_iv
    -in deploy/deploy_rsa.enc -out deploy_rsa -d
  - |
    echo $TRAVIS_BRANCH; echo $TRAVIS_PULL_REQUEST; echo $TOXENV;
    if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' && $TOXENV == 'py37' ]]; then
      eval "$(ssh-agent -s)" # start the ssh agent
      chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa # this key should have push access
      ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
      rm -f $TRAVIS_BUILD_DIR/deploy_rsa
      git remote add deploy yacoma@yacoma.it:git/auth-boilerplate.git
      git push deploy master -f
    fi
