site_name: Auth-Boilerplate
site_description:
  Boilerplate for a authentication workflow based on Morepath and Cerebral
site_dir: html

repo_url: https://github.com/yacoma/auth-boilerplate

theme: readthedocs
theme_dir: 'docs/custom_theme'

pages:
    - Indroduction: 'index.md'
    - RESTful Server:
        - Quick Start: 'server/quick-start.md'
        - REST-API: 'server/api.md'
        - Softwarestack: 'server/softwarestack.md'
    - Cerebral Client:
        - Quick Start: 'client/quick-start.md'
    - Deployment: 'deployment.md'

markdown_extensions:
    - toc:
        permalink: true
