site_name: Auth-Boilerplate
site_description:
  Boilerplate for a authentication workflow based on Morepath and Cerebral
site_dir: html

repo_url: https://github.com/yacoma/auth-boilerplate

theme: readthedocs

pages:
- Indroduction: 'index.md'
- RESTful Server:
  - Quick Start: 'server/quick-start.md'
  - API: 'server/api.md'
- Cerebral Client:
  - Quick Start: 'client/quick-start.md'
- Deployment: 'deployment.md'
