---
login:
  email:
    type: string
    coerce: normalize_email
    required: true
  password:
    type: string
    minlength: 5
    required: true

send_reset_email:
  email:
    type: string
    coerce: normalize_email
    required: true

reset_password:
  password:
    type: string
    minlength: 5
    required: true

user:
  nickname:
    type: string
    minlength: 3
    required: true
  email:
    type: string
    check_with: verify_email
    coerce: normalize_email
    required: true
  password:
    type: string
    minlength: 5
    required: true
  groups:
    type: list
    schema:
      type: string

group:
  name:
    type: string
    required: true
  users:
    type: list
    schema:
      type: string
