---
jwtauth:
  master_secret: b894da6ab8d041e9a9ec8507644c4413
  expiration_delta: 600
  leeway: 60
  allow_refresh: true
  refresh_nonce_handler: 'server.handler.refresh_nonce_handler'

database:
  provider: sqlite
  args:
    - auth.db
  kwargs:
    create_db: true

smtp:
  username: null
  password: null
  host: mail.yacoma.it
  port: '587'
  starttls: true
  smtp_skip_login: false

token:
  secret: edba63b558ae4aee9ce47c38e48b6e5b
  max_age: 604800
