---
jwtauth:
  master_secret: 13ad14ebf1644e50bdfdfe0d47c37d2d

database:
  provider: sqlite
  args:
    - auth.db
  kwargs:
    create_db: true

smtp:
  username: admin@yacoma.it

token:
  secret: e07763a54d6e422aa5b37ee1e60c4d05
  max_age: 604800
