---
jwtauth:
  master_secret: 13ad14ebf1644e50bdfdfe0d47c37d2d

database:
  provider: postgres
  user: yacoma_auth
  password: ZGX8DnZpEF
  host: localhost
  database: yacoma_auth_boilerplate
  filename: null
  create_db: null

smtp:
  username: admin@yacoma.it

token:
  secret: e07763a54d6e422aa5b37ee1e60c4d05
  max_age: 604800
