---
jwtauth:
  master_secret: 13ad14ebf1644e50bdfdfe0d47c37d2d
  leeway: 10

database:
  provider: sqlite
  args:
  - auth.db
  kwargs:
    create_db: true

authentication:
  confirm_email: true

token:
  secret: e07763a54d6e422aa5b37ee1e60c4d05
  max_age: 604800
